### ISSUE TITLE
Relative path in type import

### ISSUE THREAD

**Issue by klippx** [tulios/mappersmith#313]
Hi! Is it a known issue that mappersmith 2.39.0 that was [released yesterday](https://github.com/tulios/mappersmith/releases/tag/2.39.0) doesn’t work?

I’m getting this when doing yarn build:
```
node_modules/mappersmith/middleware/basic-auth.d.ts:1:22 - error TS2307: Cannot find module 'types' or its corresponding type declarations.

1 import { Auth } from 'types';
```

However it works with mappersmith 2.38.1.
